/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vmm_team_viewer;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author new user
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config(String ip) {
        initComponents();
        getConfiguration(ip);
        
        Dimension d= new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        
        getContentPane().setBackground(Color.white);
        
//        photoLb.setBounds(0,0,d.width,d.height);
//        ImageIcon i1 = new ImageIcon("src/uploads/configuration.jpg");
//        Image resized = i1.getImage().getScaledInstance(photoLb.getWidth(), photoLb.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon i2 = new ImageIcon(resized);
//        photoLb.setIcon(i2);

        // Icon
        ImageIcon icon = new ImageIcon("src/uploads/icon.png");
        setIconImage(icon.getImage());

        setTitle("AnyDESK - Screen Sharer App");
        setLocationRelativeTo(null);
        setSize(704, 480);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }
    
    
    
    public void getConfiguration(String ip){
        try{
            HttpResponse<String> res = Unirest.get("http://"+ip+":8000/getconfig").asString();
            
            if(res.getStatus()==200){
                String ans = res.getBody();
                
                // Tokenizing the string into parts
                StringTokenizer st = new StringTokenizer(ans,"~~");
                
                String osname = st.nextToken();
                String diskSize = st.nextToken();
                String username = st.nextToken();
                String maxMemory = st.nextToken();
                String core = st.nextToken();
                String memorySize = st.nextToken();
                
                lb1.setText("Operating System :        "+osname);
                lb2.setText("Disk Size        :        "+diskSize);
                lb3.setText("Username         :        "+username);
                lb4.setText("Maximum Memory   :        "+maxMemory);
                lb5.setText("Core Number      :        "+core);
                lb6.setText("Memory Size      :        "+memorySize);
            }
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        photoLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb1.setText("Operating System :");
        getContentPane().add(lb1);
        lb1.setBounds(30, 60, 350, 40);

        lb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb2.setText("Disk Size :");
        getContentPane().add(lb2);
        lb2.setBounds(30, 110, 350, 50);

        lb3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb3.setText("Username :");
        getContentPane().add(lb3);
        lb3.setBounds(30, 170, 350, 40);

        lb4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb4.setText("Maximum Memory :");
        getContentPane().add(lb4);
        lb4.setBounds(30, 230, 350, 40);

        lb5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb5.setText("Core Number :");
        getContentPane().add(lb5);
        lb5.setBounds(30, 290, 360, 40);

        lb6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb6.setText("Memory Size :");
        getContentPane().add(lb6);
        lb6.setBounds(30, 340, 350, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 27, 152));
        jLabel1.setText("Server's PC Configuration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 450, 60);

        jLabel2.setBackground(new java.awt.Color(250, 141, 112));
        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("AnyDESK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 400, 130, 40);

        photoLb.setText("|");
        getContentPane().add(photoLb);
        photoLb.setBounds(10, 420, 3, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uploads/configuration.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 100, 300, 270);

        setBounds(0, 0, 718, 462);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel photoLb;
    // End of variables declaration//GEN-END:variables
}
