
package vmm_team_viewer;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author sakshamchanouria
 */
public class OTP_Insert extends javax.swing.JFrame {
    String otp;
    String Gmail;
    /**
     * Creates new form OTP_Insert
     */
    public OTP_Insert(String Otp,String gmail) {
        initComponents();
        otp = Otp;
        Gmail = gmail;
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());

        photoLb.setBounds(0, 0, d.width, d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/background.jpg");
        Image resized = i1.getImage().getScaledInstance(photoLb.getWidth(), photoLb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(resized);
        photoLb.setIcon(i2);

        setVisible(true);
        setSize(500, 350);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfOTP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        photoLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 27, 152));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 280, 50);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 21, 64));
        jLabel3.setText("Enter OTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 121, 130, 30);

        tfOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOTPActionPerformed(evt);
            }
        });
        getContentPane().add(tfOTP);
        tfOTP.setBounds(240, 120, 190, 30);

        jButton1.setBackground(new java.awt.Color(255, 186, 196));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(9, 21, 64));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 230, 130, 40);

        photoLb.setText("|");
        getContentPane().add(photoLb);
        photoLb.setBounds(30, 10, 3, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOTPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
//        JOptionPane.showMessageDialog(this, otp);
          if(tfOTP.getText().equals(otp)){
              try{
                  JOptionPane.showMessageDialog(this, "OTP matched.");
                  UpdatePassword obj = new UpdatePassword(Gmail);
                  dispose();
                    
              }
              catch(Exception e){
                  e.printStackTrace();
              }
          }
          else{
              ForgotPassword obj = new ForgotPassword();
              JOptionPane.showMessageDialog(this, "You have entered Wrong OTP. Try Again!!");
              dispose();
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTP_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTP_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTP_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTP_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTP_Insert("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel photoLb;
    private javax.swing.JTextField tfOTP;
    // End of variables declaration//GEN-END:variables
}
