/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vmm_team_viewer;

import java.sql.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sakshamchanouria
 */
public class UpdatePassword extends javax.swing.JFrame {

    String gmail;

    /**
     * Creates new form UpdatePassword
     */
    public UpdatePassword(String Gmail) {
        initComponents();
        gmail = Gmail;

        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());

        photoLb.setBounds(0, 0, d.width, d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/background.jpg");
        Image resized = i1.getImage().getScaledInstance(photoLb.getWidth(), photoLb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(resized);
        photoLb.setIcon(i2);

        setVisible(true);
        setSize(570, 350);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passLb1 = new javax.swing.JLabel();
        passLb2 = new javax.swing.JLabel();
        photoLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 27, 152));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 280, 50);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 21, 64));
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 120, 130, 30);

        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        tfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPassKeyReleased(evt);
            }
        });
        getContentPane().add(tfPass);
        tfPass.setBounds(240, 120, 190, 30);

        jButton1.setBackground(new java.awt.Color(255, 186, 196));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(9, 21, 64));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 220, 130, 40);

        passLb1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        passLb1.setForeground(new java.awt.Color(255, 0, 0));
        passLb1.setText("  ");
        getContentPane().add(passLb1);
        passLb1.setBounds(440, 120, 230, 20);

        passLb2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        passLb2.setForeground(new java.awt.Color(255, 0, 0));
        passLb2.setText(" ");
        getContentPane().add(passLb2);
        passLb2.setBounds(440, 140, 180, 15);

        photoLb.setText("jLabel2");
        getContentPane().add(photoLb);
        photoLb.setBounds(30, 30, 42, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String newPass = tfPass.getText();

//        // Anshu Laptop
//        ResultSet rs = DBLoader.executeSQL("Select * from project.user where gmail='" + gmail + "'");

        // LocalHost
        ResultSet rs = DBLoader.executeSQL("Select * from test3.user where gmail='" + gmail + "'");
        try {
            if (rs.next()) {
                if (newPass.length() >= 6) {
                    rs.updateString("password", newPass);
                    rs.updateRow();
                    JOptionPane.showMessageDialog(this, "Password Changed.");
                    Login obj = new Login();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Password should contain atleast 6 characters.");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Server Error.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassKeyReleased
        // TODO add your handling code here:
        String pass = tfPass.getText();
        if (pass.length() >= 6 || pass.length() == 0) {
            passLb1.setText("");
            passLb2.setText("");
        } else {
            passLb1.setText("*Password should be");
            passLb2.setText("atleast 6 characters");
        }
    }//GEN-LAST:event_tfPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePassword("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel passLb1;
    private javax.swing.JLabel passLb2;
    private javax.swing.JLabel photoLb;
    private javax.swing.JTextField tfPass;
    // End of variables declaration//GEN-END:variables
}
